---
title: "STA457 Quiz1"
author: "Harold Hyun Woo Lee"
date: "10/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(timeSeries)
library(tidyquant)
library(tidyverse)
library(forecast)
library(highcharter)
library(ggplot2)
library(knitr)
library(gridExtra)
```

```{r}
# The symbols vector holds our tickers. 
# tickers <- c("FB", ,"TSLA","AMZ")
# pick the stock assigned to you
tickers<-c("TSLA")
# The prices object will hold the raw price data fetching from yahoo finance
prices <- getSymbols(tickers, src = 'yahoo', from = "2012-06-01",  to = "2020-09-30",auto.assign = TRUE, warnings = FALSE)

# Use the following comments to see what is contained in prices
get(prices)%>%names()

# pick up adjusted close price
price.adj = get(prices)[,6]

# summary statistics of daily adjusted closed prices
summary(price.adj)%>%kable(digits =4, format = "html")
```   
```{r}
hc <- highchart(type = "stock") %>%
        hc_title(text = "Charting stock price") %>%
        hc_add_series(price.adj)%>%
        hc_add_theme(hc_theme_flat())
hc

# You may also try
autoplot(price.adj)+theme_minimal()
```
```{r}
mPrice = to.monthly(price.adj)[,4]%>%         # transform daily prices to monthly prices
  as.ts(start = start(to.monthly(price.adj))) # casting to R ts object

ts.plot(mPrice, main = "Plot monthly stock price time series", ylab="price"); grid()

# stl
stl(mPrice,s.window = "per")%>%autoplot()+theme_minimal()

# decompose
decompose(mPrice)%>%autoplot()+theme_minimal()
```
```{r}
par(mfrow=c(1,2))
ts.plot(stl(mPrice, s.window = "per")$time.series[,"trend"], main="STL trend", ylab="")
lines(decompose(mPrice)$trend, col=2, lty="dashed")

ts.plot(stl(mPrice, s.window = "per")$time.series[,"seasonal"], main="STL seasonal", ylab="")
lines(decompose(mPrice)$seasonal, col=2, lty="dashed")

p3 = autoplot(decompose(mPrice)$random)+
        ggtitle("decompe-irregular")+ ylab("")+
        theme_minimal()
p4 = autoplot(stl(mPrice, s.window = "per")$time.series[,"remainder"])+
        ggtitle("STL-irregular")+ ylab("")+
        theme_minimal()
p1 = ggAcf(decompose(mPrice)$random, na.action = na.omit)+
        ggtitle("decompe-ACF")+
        theme_minimal()
p2 = ggPacf(stl(mPrice, s.window = "per")$time.series[,"remainder"])+
        ggtitle("STL-ACF")+
        theme_minimal()
grid.arrange(p3, p4, p1,p2, ncol=2)
```
```{r}
#Constructing ACF Plot from scratch
# calculate the length of time series
nd = decompose(mPrice)$random%>%complete.cases()%>%length()
ns = length(stl(mPrice, s.window = "per")$time.series[,"remainder"])
# pick the values of sample ACF functions lag = 0 to 24
mlag =24
acfs = acf(decompose(mPrice)$random, na.action = na.omit, plot = FALSE, lag.max = mlag)$acf%>%c()
mi = min(acfs[-1])
ma = max(acfs[-1])
ub = 2*sqrt(1/nd)
barplot(acfs[-1], ylim = c(mi-0.3,ma+0.3), col="lightblue")
abline(h = 2*sqrt(1/nd), col = "red", lty ="dotted", lwd = 2)
abline(h = -2*sqrt(1/nd), col = "orange", lty = "dotted", lwd = 2)

#Finding the largest significant lag
nq.ma.decomp = c((abs(acfs[-1])>(2*sqrt(1/nd)))*(1:mlag))%>%max()
print(nq.ma.decomp)

#Repeat the calculation again
acfs = acf(stl(mPrice, s.window = "per")$time.series[,"remainder"], 
           na.action = na.omit, plot = FALSE, lag.max = mlag)$acf%>%c()
mi = min(acfs[-1])
ma = max(acfs[-1])
ub = 2*sqrt(1/nd)
barplot(acfs[-1], ylim = c(mi-0.3,ma+0.3), col="lightgray")
abline(h = 2*sqrt(1/nd), col = "red", lty ="dotted", lwd = 2)
abline(h = -2*sqrt(1/nd), col = "orange", lty = "dotted", lwd = 2)

#Select the Best MA models based on ACF
nq.ma.stl = c((abs(acfs[-1])>(2*sqrt(1/nd)))*(1:mlag))%>%max()
print(nq.ma.stl)

print(acfs)

```





